---

- name: Generate or load the password for rspamd
  no_log: '{{ hide_secrets }}'
  ansible.builtin.set_fact:
    rspamd_password: >-
      {{ lookup(creds.store,
      creds.prefix + "rspamd/admin"
      + creds.opts.create + creds.opts.system) }}
  tags: facts, passwd

- name: Encrypt the password
  no_log: '{{ hide_secrets }}'
  register: rspamd_password_fact
  ansible.builtin.command: 'rspamadm pw -p "{{ rspamd_password | quote }}"'
  changed_when: false
  tags: facts, passwd

- name: Store the encrypted password
  ansible.builtin.set_fact:
    rspamd_password: '{{ rspamd_password_fact.stdout }}'
  tags: facts, passwd
