#!/bin/bash

# Exit on error
set -e

# Not used for now
# remote="$1"
# url="$2"

# Create the logs directory if not exists. It is ignored by git anyway
test -d logs || mkdir logs

# Check if ansible lint is installed
lint_version=$(ansible-lint --version 2>&1)
echo "Check if ansible-lint is installed and accessible: $lint_version"

# Run ansible lint on the installation playbooks
ansible-lint install/playbooks/main.yml | tee logs/ansible-lint-install.log

# Run ansible lint on the test playbooks
ansible-lint tests/playbooks/main.yml | tee logs/ansible-lint-tests.log
