---

- name: Install the required packages
  include_tasks: packages.yml

- name: Install the certificates
  include_tasks: certs.yml

- name: Configure network settings
  include_tasks: network.yml

- name: Load ldap facts
  include_tasks: facts.yml

- name: Set some configuration files
  include_tasks: config.yml

- name: Configure sieve scripts
  include_tasks: sieve.yml

- name: Configure antispam
  include_tasks: antispam.yml

- name: Import imersonate tasks
  when: mail.impersonate.active
  include_tasks: impersonate.yml

- name: Import dovecot access check tasks
  when: access_check.active
  include_tasks: access-check.yml

- name: Run import tasks
  when: mail.import.active
  include_tasks: import.yml

- name: AppArmor tasks
  include_tasks: apparmor.yml

- name: Backup configuration tasks
  include_tasks: backup.yml

- name: Include full text search tasks
  when: mail.fts.active
  include_tasks: fts.yml

- name: Include virtual mailboxes tasks
  tags: virtual
  when: mail.virtual_folders.active
  include_tasks: virtual.yml
