---

- name: Make sure loopback interface is "trusted"
  notify: Restart dovecot
  replace:
    path: /etc/dovecot/dovecot.conf
    regexp: '^#?\s?login_trusted_networks.*'
    replace: 'login_trusted_networks = 127.0.0.1 ::1'

- name: Ensure the imap server FQDN resolves to localhost
  tags: dovecot
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1    imap.{{ network.domain }}'
