---

- name: Restart the ldap service
  service:
    name: '{{ service.name }}'
    state: '{{ service.state }}'
  with_items:
    - name: unscd
      state: stopped
    - name: nslcd
      state: stopped
    - name: slapd
      state: restarted
    - name: nslcd
      state: started
    - name: unscd
      state: started
  loop_control:
    loop_var: service
