---

- name: Remove the private key
  ansible.builtin.file:
    path: /etc/wireguard/private-key
    state: absent
  tags: keys

- name: Remove the public key
  ansible.builtin.file:
    path: /etc/wireguard/public-key
    state: absent
  tags: keys
