---

# This is checking that the DNS server has been fully propagated
- name: Check DNS propagation
  register: external_ip_check
  shell: >-
    host main.{{ network.domain }}
  retries: '{{ bind.propagation.retries | default(10) }}'
  delay: '{{ bind.propagation.delay | default(60) }}'
  until: external_ip_check.rc == 0

# This is checking that the DNS server has been fully propagated
- name: Check DNS propagation for backup IP address
  register: backup_ip_check
  when: backup_ip is defined and backup_ip != ""
  shell: >-
    host backup.{{ network.domain }}
  retries: '{{ bind.propagation.retries | default(10) }}'
  delay: '{{ bind.propagation.delay | default(60) }}'
  until: backup_ip_check.rc == 0
