---

# Automatic main IP address (external_ip / IPv4)

- name: Get the external IP address automatically
  tags: facts
  register: external_ip_facts
  uri:
    url: https://api.ipify.org?format=text
    return_content: yes

- name: Store the IP address detected
  tags: facts
  set_fact:
    external_ip: '{{ external_ip_facts.content }}'

# Backup IP address (backup_ip / IPv6)
- name: Get the backup IP address automatically
  tags: facts
  register: backup_ip_facts
  uri:
    url: https://api6.ipify.org?format=text
    return_content: yes

- name: Store the backup IP address detected (if different from the first one)
  when: backup_ip_facts.content != external_ip
  tags: facts
  set_fact:
    backup_ip: '{{ backup_ip_facts.content }}'
