---

- name: Stop the systemd service
  systemd:
    name: dirsrv@localhost
    state: stopped
  ignore_errors: true

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Remove the DNS record if existing
  shell: >-
    pdnsutil delete-rrset {{ network.domain }}
    ldap CNAME
  changed_when: true
  failed_when: false

- name: Remove all the installed packages
  apt:
    name: '{{ ldap_packages.install }}'
    state: absent
    purge: true
    autoremove: true

- name: Remove the config directory
  file:
    path: /etc/dirsrv
    state: absent
