---

# Use IP addresses as SPF mechanisms for the server itself
- name: Add the external IP address as SPF sender
  set_fact:
    spf_senders: '{{ "ip6:" + external_ip if external_ip | ipv6 else "ip4:" + external_ip }}'

- name: Add the backup IP address as SPF sender
  when: backup_ip is defined and (backup_ip | length > 0)
  set_fact:
    spf_senders: '{{ spf_senders }} {{ "ip6:" + backup_ip if backup_ip | ipv6 else "ip4:" + backup_ip }}'

- name: Add the user configured extra senders to the SPF record
  when: mail.extra_senders
  set_fact:
    spf_senders: '{{ spf_senders }} {{ mail.extra_senders | join(" ") }}'

# Use "soft fail" in development mode
- name: Set the SPF qualifier as "soft fail"
  when: system.devel or system.debug
  set_fact:
    spf_qualifier: '~'

# Use "fail" (strict) otherwise
- name: Set the SPF qualifier as strict
  when: not system.devel and not system.debug
  set_fact:
    spf_qualifier: '-'

- name: Add the main external IP record
  shell: >-
    pdnsutil add-record {{ network.domain }}
    smtp {{ external_ip_type }} {{ external_ip }}

- name: Add the main external IP record
  when: backup_ip is defined and backup_ip != ""
  shell: >-
    pdnsutil add-record {{ network.domain }}
    smtp2 {{ backup_ip_type }} {{ backup_ip }}
