---

# See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858587
- name: Fix a bug in fail2ban configuration
  notify: Restart fail2ban
  replace:
    path: /etc/fail2ban/jail.conf
    regexp: 'imap3,'
    replace: ''

# Create an empty mail.warn configuration, to let fail2ban start
- name: Create an empty mail.warn
  file:
    path: /var/log/mail.warn
    state: touch

# Some misconfigured servers are generating a lot of errors
# While this is happening before authentication, this generates
# a lot of noise and can be problematic to extract
# useful information from log files
- name: Add custom postfix fail2ban rule to reduce noise
  notify: Restart fail2ban
  template:
    src: fail2ban-noise-reduction.conf
    dest: /etc/fail2ban/filter.d/postfix-nr.conf

- name: Add sections in the jail config
  notify: Restart fail2ban
  ini_file:
    path: /etc/fail2ban/jail.conf
    section: 'postfix-nr'
    option: '{{ option.name }}'
    value: '{{ option.value }}'
    create: yes
  with_items:
    - name: port
      value: smtp,submissions,submission
    - name: logpath
      value: '%(postfix_log)s'
    - name: backend
      value: '%(postfix_backend)s'
    - name: enabled
      value: True
    - name: bantime
      value: '{{ mail.fail2ban.time }}'
  loop_control:
    loop_var: option

- name: Activate fail2ban on postfix
  notify: Restart fail2ban
  ini_file:
    path: /etc/fail2ban/jail.conf
    section: '{{ section }}'
    option: enabled
    value: true
    create: no
  with_items:
    - postfix
    - postfix-sasl
    - postfix-rbl
  loop_control:
    loop_var: section

- name: Set fail2ban time
  notify: Restart fail2ban
  ini_file:
    path: /etc/fail2ban/jail.conf
    option: bantime
    section: '{{ section }}'
    value: '{{ mail.fail2ban.time }}'
    create: no
  with_items:
    - postfix
    - postfix-sasl
    - postfix-rbl
  loop_control:
    loop_var: section
