#!/bin/dash

UID=$1

USERS=$(getent passwd | grep ':100[0-9]' | sed 's/:.*//g' | tr '\n' ',')

if [ "$UID" = "" ]; then
    echo "Usage: $0 <uid>"
    echo "uid: User ID (e.g. $USERS)"
    exit 1
fi

PASSWORD='{{ lookup("password", ldap.adminPasswdParams) }}'
BASE='{{ ldap.users.dn }}'
BIND='{{ ldap.admin.dn }}'
HOST='ldap.{{ network.domain }}'

ldapvi -b "$BASE" -Z -w"$PASSWORD" -D "$BIND" -h "$HOST" uid="$UID"
