---

- name: Remove conflicting packages first
  apt:
    name: '{{ ldap_packages.remove }}'
    state: absent
    purge: true

- name: Install the required packages
  apt:
    name: '{{ ldap_packages.install }}'
    state: present

- name: Create the configuration init directory
  file:
    path: /etc/dirsrv/init/
    state: directory
    owner: dirsrv
    group: dirsrv
    mode: 0600

- name: Create the initial configuration
  register: ldap_config
  template:
    src: dscreate.conf
    dest: /etc/dirsrv/init/dscreate.conf
    owner: dirsrv
    group: dirsrv
    mode: 0600

- name: Load the configuration
  when: ldap_config.changed
  shell: >-
    dscreate -v from-file dscreate.conf
  args:
    chdir: /etc/dirsrv/init/
  changed_when: true

- name: Copy the organization unit definition file
  register: ou_config
  template:
    src: 389ds_ou.ldif
    dest: /etc/dirsrv/init/389ds_ou.ldif
    owner: dirsrv
    group: dirsrv
    mode: 0600

- name: Create the organization unit for users
  shell: >-
    dsidm
    --basedn '{{ ldap.organization.base }}'
    localhost organizationalunit create
    --ou users
  changed_when: true
