---

- name: Check if the password quality module is in place
  register: line_found
  shell: >-
    grep -c pam_pwquality
    /etc/pam.d/common-password
  changed_when: false
  failed_when: false

- name: Build password quality parameters string
  when: passwords.quality.enforce
  set_fact:
    pwq_params: '{{ pwq_params | default("") }}{{ item.name }}={{ item.value }} '
  with_items:
    - '{{ passwords.quality.params }}'

- name: Configure password quality module
  when: passwords.quality.enforce and line_found.stdout == '0'
  replace:
    path: /etc/pam.d/common-password
    regexp: '^password\s+requisite\s+pam_pwquality.so.*$'
    replace: 'password requisite pam_pwquality.so {{ pwq_params | trim() }}'

- name: Configure password quality module
  when: passwords.remember > 0
  replace:
    path: /etc/pam.d/common-password
    regexp: '^(password.*pam_unix.so.*sha512)$'
    replace: '\1 remember={{ passwords.remember }}'
