{
 "title": "System load",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance=\"127.0.0.1:9100\"}",
     "legendFormat": "Load average (1mn)"
    },
    {
     "expr": "node_load5{instance=\"127.0.0.1:9100\"}",
     "legendFormat": "Load average (5mn)"
    },
    {
     "expr": "node_load15{instance=\"127.0.0.1:9100\"}",
     "legendFormat": "Load average (15mn)"
    }
   ]
  },
  {
   "title": "Memory load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_exporter:memory:used{instance=\"127.0.0.1:9100\"}",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "node_exporter:swap:used{instance=\"127.0.0.1:9100\"}",
     "legendFormat": "Swap usage"
    }
   ]
  },
  {
   "title": "Network (IPv4)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(node_netstat_IpExt_InOctets{instance=\"127.0.0.1:9100\"}[5m])",
     "legendFormat": "In"
    },
    {
     "expr": "rate(node_netstat_IpExt_OutOctets{instance=\"127.0.0.1:9100\"}[5m])",
     "legendFormat": "Out"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs[5m])",
     "legendFormat": "Retransmissions"
    }
   ]
  },
  {
   "title": "Network (IPv6)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(node_netstat_Ip6_InOctets{instance=\"127.0.0.1:9100\"}[5m])",
     "legendFormat": "In"
    },
    {
     "expr": "rate(node_netstat_Ip6_OutOctets{instance=\"127.0.0.1:9100\"}[5m])",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Filesystem space usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - 100 * node_filesystem_avail_bytes{instance=\"127.0.0.1:9100\"}/node_filesystem_size_bytes{instance=\"127.0.0.1:9100\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem inodes usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - 100 * node_filesystem_files_free / node_filesystem_files",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_alerts{instance=\"127.0.0.1:9093\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}