---

- name: Install isync package
  apt:
    name: isync
    state: latest

# Get the import master account password
- name: Initialise the import user password parameters
  set_fact:
    import_password_params: "{{ playbook_dir }}/../../backup/{{ network.domain }}/ldap/import.pwd {{ policies.system.password }}"

- name: Create the import master user account password
  set_fact:
    import_password: '{{ lookup("password", import_password_params) }}'

- name: Build a template for each account and each user, and encrypt it using the system key
  include_tasks: roles/import-accounts/tasks/isync-template.yml
  with_items:
    - '{{ users }}'
  loop_control:
    loop_var: user

- name: Copy the postlogin scripts to start emails import on each user login
  notify: Restart dovecot
  tags: scripts
  copy:
    src: import-emails
    dest: /etc/dovecot/login-scripts/500-import-emails
    mode: '0755'
    owner: root
    group: root
