---

- name: Create the lego directory to store the certificates
  ansible.builtin.file:
    path: /etc/lego
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags: preinstall

- name: Create the lego configuration directory
  ansible.builtin.file:
    path: /var/lib/lego
    state: directory
    mode: '0750'
    group: ssl-cert
  tags: preinstall

- name: Create the directory to store certificates files
  ansible.builtin.file:
    path: /var/lib/lego/certificates
    state: directory
    mode: '0750'
    group: ssl-cert
  tags: preinstall

- name: Link for compatibility with lego executable
  ansible.builtin.file:
    src: /var/lib/lego/certificates
    dest: /etc/lego/certificates
    state: link
  tags: preinstall

- name: Get the DNS api key
  no_log: '{{ hide_secrets }}'
  ansible.builtin.set_fact:
    api_key: '{{ lookup(creds.store, creds.prefix + "/dns/api-key") }}'
  tags: preinstall

# LetsEncrypt will need to be accessed once the DNS server is live.
- name: Allow LetsEncrypt web site access in the proxy
  notify: Restart tinyproxy
  ansible.builtin.lineinfile:
    path: /etc/tinyproxy/filter
    line: '^acme-v02\.api\.letsencrypt\.org$'
  tags: preinstall, proxy
