---

- name: Install nginx AppArmor profile
  notify:
    - Activate AppArmor profile
    - Restart AppArmor service
    - Restart nginx
  template:
    src: apparmor.d/local/mta-sts.conf
    dest: /etc/apparmor.d/local/mta-sts

- name: Check if AppArmor nginx configuration already contains the line
  register: line_found
  shell: >-
    grep -c 'include <local/mta-sts>'
    /etc/apparmor.d/usr.sbin.nginx
  changed_when: false
  failed_when: false

- name: Add AppArmor specific configuration
  when: line_found.stdout == '0'
  notify:
    - Activate AppArmor profile
    - Restart AppArmor service
    - Restart nginx
  lineinfile:
    path: /etc/apparmor.d/usr.sbin.nginx
    line: '  #include <local/mta-sts>'
    insertbefore: '# End of local includes for homebox'
