---

- name: Load or create the password for the read-only account
  no_log: '{{ hide_secrets }}'
  ansible.builtin.set_fact:
    ldap_ro_password: '{{ lookup(creds.store, creds.prefix + "/ldap/readonly") }}'
  tags: facts

- name: Compute the users DN
  ansible.builtin.set_fact:
    ldap_users_dn: 'ou=users,dc={{ network.domain.split(".") | join(",dc=") }}'
  tags: facts

- name: Set the readonly user’ DN
  ansible.builtin.set_fact:
    ldap_readonly_dn: 'cn=readonly account,{{ ldap_users_dn }}'
  tags: facts

- name: Create or get the database account password
  no_log: '{{ hide_secrets }}'
  ansible.builtin.set_fact:
    ejabberd_db_password: >-
      {{ lookup(creds.store, creds.prefix + "/postgresql/ejabberd"
      + creds.opts.create + creds.opts.system) }}
  tags: facts

- name: Read port ranges to use
  register: ephemeral_ports_cmd
  ansible.builtin.shell: >-
    set -o pipefail;
    sysctl -n net.ipv4.ip_local_port_range
    | tr '\t' '-'
  args:
    executable: /bin/bash
  changed_when: false
  tags: facts

- name: Store the ephemeral ports
  ansible.builtin.set_fact:
    ephemeral_ports: '{{ ephemeral_ports_cmd.stdout }}'
  tags: facts
