---

- name: Deploy IMAP private access firewall rules
  notify: Restart nftables
  ansible.builtin.template:
    src: nftables/imap-private.nft
    dest: /etc/nftables/30-imap.nft
    validate: nft -c -f "%s"
    mode: '0600'
  tags: firewall

- name: Deploy POP3 private access firewall rules
  when: mail.pop3
  notify: Restart nftables
  ansible.builtin.template:
    src: nftables/pop3-private.nft
    dest: /etc/nftables/30-pop3.nft
    validate: nft -c -f "%s"
    mode: '0600'
  tags: firewall

- name: Restart the firewall now if needed
  ansible.builtin.meta: flush_handlers
  tags: firewall
