---

- name: Install ipcalc-ng for the login script
  ansible.builtin.apt:
    name: ipcalc-ng
    state: present
  tags: post-login

- name: Add the login script to whitelist IPs on successful authentication
  when: mail.protection.type != "public"
  ansible.builtin.copy:
    src: scripts/post-login-script.sh
    dest: /usr/local/sbin/dovecot-post-login
    mode: '0755'
  tags: post-login
