---

# Install automatic configuration for Mozilla Thunderbird
- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: autoconfig
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  roles:
    - role: certificates
      tags: certificates
    - autoconfig
