---

# Crate the certificate for the jabber/xmpp server
- hosts: homebox
  vars:
    certificate:
      type: xmpp
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  roles:
    - role: certificates
      tags: certificates
