---

# Install a basic web site in http and https
- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: www
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  roles:
    - role: certificates
      tags: certificates

- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: '@'
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  roles:
    - role: certificates
      tags: certificates

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  roles:
    - role: website-simple
      tags: website
