---

- name: Deploy the firewall rules
  notify: Restart firewall
  ansible.builtin.template:
    src: nftables/firewall-{{ mail.protection.type }}.nft
    dest: /etc/nftables/60-postfix.nft
    mode: '0600'
  tags: firewall
