---

csp_default:
  default: "'none'"
  list:
    - id: default-src
    - id: script-src
    - id: img-src
    - id: style-src
    - id: media-src
    - id: font-src
    - id: base-uri
    - id: frame-src
    - id: object-src
    - id: connect-src

### Features policy
# See https://github.com/w3c/webappsec-feature-policy
# Set to 'none' by default
fp_default:
  default: "'none'"
  list:
    - id: geolocation
    - id: midi
    - id: notifications
    - id: push
    - id: sync-xhr
    - id: microphone
    - id: camera
    - id: magnetometer
    - id: gyroscope
    - id: speaker
    - id: vibrate
    - id: fullscreen
    - id: payment
