---

# Main IP address
- name: Build reverse IP address using shell
  shell: >-
    dig -x {{ external_ip }}
    @{{ bind.forward[0] }}
    | awk 'f{print;f=0} /^;; QUESTION SECTION:/{f=1}'
    | sed -E 's/(^;|.IN.*)//g'
  register: reverse_main_ip

- name: Build the reverse IP address (works for IPv4 or IPv6)
  tags: facts
  set_fact:
    reverse_ip: "{{ reverse_main_ip.stdout }}"

# Backup IP address
- name: Build reverse IP address using shell
  when: backup_ip is defined and backup_ip != ""
  shell: >-
    dig -x {{ network.backup_ip }}
    @{{ bind.forward[0] }}
    | awk 'f{print;f=0} /^;; QUESTION SECTION:/{f=1}'
    | sed -E 's/(^;|.IN.*)//g'
  register: reverse_backup_ip

- name: Build the reverse IP address (works for IPv4 or IPv6)
  when: backup_ip is defined and backup_ip != ""
  tags: facts
  set_fact:
    reverse_backup_ip: "{{ reverse_backup_ip.stdout }}"
