{
 "title": "Nginx",
 "description": "Nginx web server",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-node_systemd_unit_start_time_seconds{name=\"nginx.service\"}",
     "legendFormat": "UP time"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted[5m])",
     "legendFormat": "Accepted"
    },
    {
     "expr": "rate(nginx_connections_active[5m])",
     "legendFormat": "Active"
    },
    {
     "expr": "rate(nginx_connections_handled[5m])",
     "legendFormat": "Handled"
    },
    {
     "expr": "rate(nginx_connections_waiting[5m])",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])",
     "legendFormat": "Requests"
    },
    {
     "expr": "rate(nginx_connections_reading[5m])",
     "legendFormat": "Reading"
    },
    {
     "expr": "rate(nginx_connections_writing[5m])",
     "legendFormat": "Writing"
    }
   ]
  }
 ]
}