{
 "title": "PowerDNS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pdns_auth_udp_queries[$__rate_interval])",
     "legendFormat": "Queries (UDP)"
    },
    {
     "expr": "rate(pdns_auth_udp_answers[$__rate_interval])",
     "legendFormat": "Answers (UDP)"
    },
    {
     "expr": "rate(pdns_auth_tcp_queries[$__rate_interval])",
     "legendFormat": "Queries (TCP)"
    },
    {
     "expr": "rate(pdns_auth_tcp_answers[$__rate_interval])",
     "legendFormat": "Answers (TCP)"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(pdns_auth_query_cache_hit[$__rate_interval])",
     "legendFormat": "Cache hit"
    },
    {
     "expr": "rate(pdns_auth_query_cache_miss[$__rate_interval])",
     "legendFormat": "Cache miss"
    },
    {
     "expr": "rate(pdns_auth_backend_queries[$__rate_interval])",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Performances and resources",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pdns_auth_latency", "legendFormat": "Latency" },
    { "expr": "pdns_auth_real_memory_usage", "legendFormat": "Memory usage" },
    { "expr": "pdns_auth_query_cache_size", "legendFormat": "Queries cached" },
    { "expr": "pdns_auth_signature_cache_size", "legendFormat": "Signatures cache" },
    { "expr": "floor(pdns_auth_uptime/86400)", "legendFormat": "Uptime (days)" }
   ]
  }
 ]
}