---

- name: Load network information
  ansible.builtin.include_tasks: install/facts.yml
  tags: facts

- name: Install the required packages
  ansible.builtin.include_tasks: install/packages.yml

- name: Prepare logging settings
  ansible.builtin.include_tasks: install/logging.yml
  tags: logging

- name: Set the generic firewall rules
  ansible.builtin.include_tasks: install/rules.yml
  tags: rules

- name: Create sets to store trusted and banned networks
  when: security.autoban.active
  ansible.builtin.include_tasks: install/autoban.yml
  tags: rules, autoban, scripts

- name: Deploy other utility scripts
  ansible.builtin.include_tasks: install/scripts.yml
  tags: scripts

- name: Set the remote access firewall rules for private networks
  ansible.builtin.include_tasks: install/private-access.yml
  tags: rules

- name: Configure SSH
  ansible.builtin.include_tasks: install/ssh-config.yml
  tags: ssh

- name: Start the firewall
  ansible.builtin.include_tasks: install/start.yml
  tags: systemd
