---

# nginx security headers mta-sts
nginx_sec_headers:
  - id: Strict-Transport-Security
    value: max-age=31536000
  - id: X-Content-Type-Options
    value: nosniff
  - id: Referrer-Policy
    value: same-origin
  - id: X-Frame-Options
    value: sameorigin

csp_default:
  default: "'self'"
  list:
    - id: default-src
      value: "https: 'self'"
    - id: script-src
      value: "https: 'self' 'unsafe-inline'"
    - id: img-src
      value: "https: 'self' 'unsafe-inline'"
    - id: style-src
      value: "https: 'self' 'unsafe-inline'"
    - id: media-src
      value: "https: 'self'"
    - id: font-src
      value: "https: 'self'"
    - id: base-uri
      value: "https: 'self'"
    - id: frame-src
    - id: object-src
    - id: connect-src


### Features policy
# See https://github.com/w3c/webappsec-feature-policy
# Set to 'none' by default
fp_default:
  default: "'none'"
  list:
    - id: geolocation
    - id: midi
    - id: notifications
    - id: push
    - id: sync-xhr
    - id: microphone
    - id: camera
    - id: magnetometer
    - id: gyroscope
    - id: speaker
    - id: vibrate
    - id: fullscreen
    - id: payment
