version: '3'
services:
  pebble:
    image: letsencrypt/pebble:latest
    # Might need '-strict false' in the future
    command: pebble -config /test/config/pebble-config.json -dnsserver 10.30.50.3:8053
    environment:
      # TODO(@cpu): Delete this explicit GODEBUG env var once Pebble is built
      # with Go 1.13.x which defaults TLS 1.3 to on
      GODEBUG: "tls13=1"
    ports:
      - 14000:14000  # HTTPS ACME API
      - 15000:15000  # HTTPS Management API
    environment:
      - PEBBLE_VA_NOSLEEP=1       # No delay
      - PEBBLE_WFE_NONCEREJECT=0  # Do not test the client's error handling
    volumes:
      - ./pebble/pebble-config.json:/test/config/pebble-config.json
    networks:
      acmenet:
        ipv4_address: 10.30.50.2
  challtestsrv:
    image: letsencrypt/pebble-challtestsrv:latest
    command: pebble-challtestsrv -defaultIPv6 "" -defaultIPv4 10.30.50.3
    ports:
      - 8055:8055  # HTTP Management API
    networks:
      acmenet:
        ipv4_address: 10.30.50.3
  apt-cacher:
    build: apt-cacher
    ports:
      - 3142:3142
    volumes:
      - apt-cache:/var/cache/apt-cacher-ng
    networks:
      acmenet:
        ipv4_address: 10.30.50.4

networks:
  acmenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.50.0/24

volumes:
  apt-cache:
