---

# Uninstall eJabberd
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../config/defaults.yml'
  vars:
    certificate:
      type: conference
  roles:
    - certificates

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../config/defaults.yml'
  vars:
    certificate:
      type: xmpp
  roles:
    - certificates

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../config/defaults.yml'
  roles:
    - role: ejabberd
      tags: uninstall
