---

- name: Restart AppArmor service
  service:
    name: apparmor
    state: restarted

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Activate AppArmor profile
  command: 'aa-enforce usr.sbin.nginx'
