---
# Example file to create an ISO image installer with Debian preseed.

# 1. Setup SSH authentication:
# Copy your public key in "preseed/misc/root/.ssh/authorized_key".
# This key will be copied into the /root/.ssh/authorized_keys for you to connect to your linux server

# 2. Customisation:
# Copy this file to system.yml, and modify the values accordingly
# You can use a dedicated Linux machine as an ISO image builder, or use your workstation.
# Associated with libvirt, and snapshots, it can be used as a development environment for the mail server.

# 3. Build the ISO image
# Example of a command to run to build the ISO image
# ansible-playbook -v -i ../config/hosts.yml playbooks/build-cd.yml
# This will create the ISO images in /tmp folder. Use the DVD one for automatic installation.

# 4. Use a physical server or a VM to run the Debian installer.
# The whole installation should be automatic, with LVM and software RAID
# For LVM, there is a volume called "reserved" you can remove. This will let
# you resize the other volumes according to your needs.

# 5. See the documentation and the Ansible scripts into the install folder to install the mail server platform.

# Remember: http://imgs.xkcd.com/comics/security.png
# So, here some good passphrases:
# - Can I have some water, please?
# - I am tired, I want to sleep.
# - I will not give you my password.
# - etc...

# System configuration sample 1: Encrypted hard drive
# system:
#   hostname: mail
#   preseed: luks
#   version: 9.13
#   arch: amd64
#   boot_timeout: 5   # In seconds
#   passphrase: I will not give you my password
#   hw:
#     disks:
#       - name: vda
#         size: 500G

# System configuration sample 2: Software RAID
# WORK IN PROGRESS, NOT FULLY TESTED YET
# TODO: Add encryption support (ecryptfs?)
# system:
#   hostname: mail
#   preseed: raid
#   version: 9.13
#   arch: amd64
#   boot_timeout: 5   # In seconds
#   hw:
#     disks:
#       - name: vda
#         size: 500G
#       - name: vdb
#         size: 500G

# System configuration sample 3: Simple LVM
# WORK IN PROGRESS, NOT FULLY TESTED YET
# TODO: Add encryption support (ecryptfs?)
# system:
#   hostname: mail
#   preseed: lvm
#   version: 9.13
#   arch: amd64
#   boot_timeout: 5   # In seconds
#   hw:
#     disks:
#       - name: vda
#         size: 500G
#       - name: vdb
#         size: 500G

# The proxy is optional. When specified, it is used to configure apt
network:
  # proxy:               # something like http://proxy.example.com:3128/
  domain: example.com
  iface: auto            # or use eth0, ens3, etc...

# Country and locales definition
country:
  code: uk
  timezone: Europe/London

locale:
  id: en_GB
  language: en
  country: UK
  charset: UTF-8
  keymap: gb

# Repository specific values
repo:
  release: stretch
  main: ftp.uk.debian.org
  security: security.debian.org
  sections: main contrib non-free

# Clock parameters
clock:
  utc: true
  ntp: true

# Accounts informations
# You can choose a strong password here,
root:
  password: H0meb0x

# Where to put the ISO image once built. If You are doing development, you can copy it to
# the libvirt/images folder.
# You should have the right to write in ths folder.
# cdimage:
#   destination: '/var/lib/libvirt/images/'

# Debug: As it states
debug: true
